import { NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { sendEmail } from '@/lib/gmail'

export async function POST(req: Request) {
  const session = await auth()
  if (!session?.user?.email || !session.googleAccessToken) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { briefing } = await req.json()
  if (!briefing) {
    return NextResponse.json({ error: 'Missing briefing data' }, { status: 400 })
  }

  const to = session.user.email
  const subject = `Your ExecutiveVAi Daily Briefing - ${new Date().toLocaleDateString()}`

  // Format the briefing into a simple HTML email
  const body = `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
      <h2 style="color: #4f46e5;">${briefing.greeting}</h2>
      <p style="color: #666; font-style: italic;">${briefing.motivationalNote || ''}</p>
      
      ${briefing.todayReminders?.length ? `
        <h3 style="border-bottom: 2px solid #eee; padding-bottom: 5px;">⏰ Today's Reminders</h3>
        <ul>
          ${briefing.todayReminders.map((r: any) => `<li><strong>${r.time}</strong>: ${r.title}</li>`).join('')}
        </ul>
      ` : ''}

      ${briefing.emailInsights?.length ? `
        <h3 style="border-bottom: 2px solid #eee; padding-bottom: 5px;">📧 Important Emails</h3>
        <ul>
          ${briefing.emailInsights.map((e: any) => `<li><strong>${e.from}</strong> - ${e.subject}<br/><small style="color:#666;">💡 ${e.action}</small></li>`).join('')}
        </ul>
      ` : ''}

      ${briefing.recommendedSchedule?.length ? `
        <h3 style="border-bottom: 2px solid #eee; padding-bottom: 5px;">📋 Recommended Schedule</h3>
        <ul>
          ${briefing.recommendedSchedule.map((s: any) => `<li><strong>${s.time}</strong> (${s.duration}): ${s.activity}</li>`).join('')}
        </ul>
      ` : ''}
      
      <p style="margin-top: 30px; font-size: 12px; color: #999;">Generated by ExecutiveVAi</p>
    </div>
  `

  try {
    const formattedBody = body.replace(/\n/g, '') // remove newlines so the gmail util doesn't inject extra <br>
    await sendEmail(session.googleAccessToken, to, subject, formattedBody)
    return NextResponse.json({ success: true })
  } catch (error: any) {
    console.error('Error sending briefing email:', error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
